### ISSUE TITLE
When I use Ubuntu image, nothing is displayed,

### ISSUE THREAD

**Issue by bebee** [linuxserver/docker-webtop#13] opened 2021-05-15 06:09 UTC
my os mac 10.15.7 (19H1030)
my docker destop version is 3.3.3 
it  is currently the newest version available

this is my docker-compuse.yml   
When I use alpine image ,everything is ok
but when i use ubuntu image,nothing is displayed

```
version: "3"
services:
  webtop:
    image: ghcr.io/linuxserver/webtop:ubuntu-kde

    container_name: webtop
    privileged: true #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
    shm_size: "5gb" #optional
    restart: unless-stopped

  caddy:
    image : caddy:2.3.0-alpine
    ports:
     - "80:80"
    
    depends_on:
     - webtop
    volumes:
     - ./caddy/data:/data
     - ./caddy/config:/config
     - ./caddy/Caddyfile:/etc/caddy/Caddyfile

```

**Comment by thelamer** [comment] 2021-05-15 07:02
No real background here as no one on the team uses Apple or docker desktop, but if I had to guess just in general privileged mode will not work on OSX. The whole purpose of privileged modes is that you are bind mounting in Linux host level stuff, OSX lacks this stuff.
Use a different flavor or stick with Alpine.

**Comment by bebee** [comment] 2021-05-15 07:19
> No real background here as no one on the team uses Apple or docker desktop, but if I had to guess just in general privileged mode will not work on OSX. The whole purpose of privileged modes is that you are bind mounting in Linux host level stuff, OSX lacks this stuff.
> Use a different flavor or stick with Alpine.

ok,i will try it in ubuntu server

**Comment by thelamer** [comment] 2021-05-16 19:45
Sorry if I was not clear, when I said flavor I meant a different flavor of Ubuntu webtop that is is not kde IE `ubuntu-xfce` or `ubuntu-mate` we know these images work that is not really the question here. I will be closing this issue as I do not believe there is anything we can do to ensure `ubuntu-kde` would work without privileged mode.

**Closed by thelamer** 2021-05-16 19:45 UTC

**Comment by IonicEcko** [comment] 2021-08-25 09:58
I'm having this same issue but the docker host is a Ubuntu Server OS.

The comments are a little confusing for me but it sounds like you were attributing the issue to a MacOS host but that doesn't appear to be the cause. Any idea what I could do to assist in troubleshooting?

OS: Ubuntu 20.04.2 LTS
Compose used from template with only change being the image tag.
